### ISSUE TITLE
Advanced search in checkboxgroup

### ISSUE THREAD

**Issue by alejaaandro** [bramley/phplist-plugin-subscribers#10]
Phplist saves multiple values of a checkboxgroup attribute in a csv. So, when searching for a value in this type of attribute, a regex should be used as to not return false positives.
Best explained with an example:

* some attribute has possible numeric values from 1-25
* if I search for "3" in that attribute, i get results for subscribers with values 3,13 and/or 23 (because they all contain the "3" that I was searching for. But this is probably not the intended result (certainly not for me)

In the case of "checboxgroup" attributes, the search function should search using this regex
"(,VAL,)|(^VAL,)|(,VAL$)" (where VAL is the value we're searching for)

This covers all cases: 
- VAL being in the middle of the csv (with a comma before and after)
- VAL being in the beginning with a comma after (to exclude possible values like "35" if I'm looking for "3")
- VAL being in the end, with a comma before (to exclude possible values like "23")

Hope I've contributed a bit :-)

It would be even better if we could search for the real value and not the numeric one in checkboxgroup, radio and select attributes.
ie. if I have a checkboxgroup for various intereste and those are saved in phplist as numeric, it would be preferable to search for the actual interest (for example "food,reading, travelling" etc ) instead of having to know or look up the numeric value that corresponds to what I'm looking for

**Comment by bramley** [comment]
Check box group attributes are a bit harder to handle. I will look into your suggestion about doing an exact match instead of a pattern match using LIKE but using the real attribute values might not be that easy to implement.

> It would be even better if we could search for the real value and not the numeric one in checkboxgroup, radio and select attributes.

That should already be the case for radio button and select attributes. You can search for the real attribute value, e.g. 'food'. As the matching uses the LIKE operator simply "fo" would also match.

**Comment by bramley** [comment]
There is a new release of the plugin that will do an exact match on the checkboxgroup attribute id (not the "real" value). So searching for 3 will match 3 but not 13 nor 23.

**Comment by alejaaandro** [comment]
Thanks, that's great! :-)
Hopefully at some point we can have "real value" search for chkbxgroups as well.
As soon as I get used to the new system and have some time, I'll try to chip in with some help

**Comment by bramley** [comment]
I have implemented displaying and searching for the real values of a checkbox group attribute.
It is a new branch in Github https://github.com/bramley/phplist-plugin-subscribers/tree/checkboxgroup

Do you mind installing that and testing it? You will need to download the zip file and install manually.

**Comment by alejaaandro** [comment]
Sorry, I've been really busy lately.. I' do it as soon as I've got some free time and let you know of any feedback
