### ISSUE TITLE
Call to undefined method phpList\plugin\Common\WebblerListing::setElementHeading()

### ISSUE THREAD

**Issue by MarcelvC** [bramley/phplist-plugin-subscribers#12]
Error message:

> Fatal error: Uncaught Error: Call to undefined method phpList\plugin\Common\WebblerListing::setElementHeading() in /admin/plugins/SubscribersPlugin/InvalidPopulator.php:53
> 
> Stack trace:
> #0 /admin/plugins/Common/Listing.php(52): phpList\plugin\SubscribersPlugin\InvalidPopulator->populate(Object(phpList\plugin\Common\WebblerListing), 0, 50)
> #1 /admin/plugins/SubscribersPlugin/Controller/Command.php(301): phpList\plugin\Common\Listing->display()
> #2 /admin/plugins/Common/Controller.php(91): phpList\plugin\SubscribersPlugin\Controller\Command->actionValidate()
> #3 /admin/plugins/Common/Main.php(44): phpList\plugin\Common\Controller->run('validate')
> #4 /admin/plugins/SubscribersPlugin/command.php(31): phpList\plugin\Common\Main::run(Object(phpList\plugin\SubscribersPlugin\ControllerFactory))
> #5 /admin/index.php(643): include('... in /admin/plugins/SubscribersPlugin/InvalidPopulator.php on line 53
> 
> phpList version 3.2.4

**Comment by bramley** [comment]
That function is present in a more recent release of phplist than you have installed, so you need to upgrade phplist. I'll update the dependencies to reflect that.

**Comment by MarcelvC** [comment]
I see, thanks for letting me know!
