### ISSUE TITLE
Export insue on Advanced Search

### ISSUE THREAD

**Issue by facilitator999** [bramley/phplist-plugin-subscribers#13]
/lists/admin/?page=details&pi=SubscribersPlugin&tk=bbfc870ea00d6a0ee72a5e0e187ee352

Shows: Subscribers
Showing 1 to 50 of 329243; 

Downloaded excel only has 82000 emails.

**Comment by bramley** [comment]
You raised a similar problem in the past https://github.com/bramley/phplist-plugin-subscribers/issues/9

**Comment by facilitator999** [comment]
Yes that post solved this issue

**Comment by bramley** [comment]
I have made some changes to try to handle exporting very large number of subscribers. Do you mind trying it? Just upgrade the Common Plugin and also the Subscribers Plugin to the latest versions.
