### ISSUE TITLE
Server Error 500 on Subscriber commands

### ISSUE THREAD

**Issue by webcompressor** [bramley/phplist-plugin-subscribers#14]
Hi,

I got the following in Apache error logs:

PHP Fatal error:  Class 'phpList\\plugin\\SubscribersPlugin\\Command\\Factory' not found in /var/www/www.example.com/lists/admin/plugins/phplist-plugin-subscribers-master/plugins/SubscribersPlugin/depends.php on line 66, referer: https://www.example.com/lists/admin/?page=plugins&tk=30b241c2c7bacd20d6d57c8b95f220e6

- PHP version 5.4.45
- PHPList version: 3.3.1
- phplist-plugin-common version: 3.7.3+20171125
- phplist-plugin-subscribers version:  2.13.0+20171111

Can you please let me know what did I miss?
Thanks a lot in advance

**Comment by bramley** [comment]
> /var/www/www.example.com/lists/admin/plugins/phplist-plugin-subscribers-master/plugins/SubscribersPlugin/depends.php 

This file path is incorrect. It looks like you installed the plugin manually, so please see the installation instructions.

**Comment by webcompressor** [comment]
Hi,
Thank you so much! It works now :-)
I'm not used to using GitHub and it's very special way of package management...
Best Regards,
