### ISSUE TITLE
Advanced Search - List Order

### ISSUE THREAD

**Issue by DanMellor** [bramley/phplist-plugin-subscribers#15]
Hi,

Love the Subscriber functionality!  Couple of tweak if possible:-

1.  Advanced Search - can the drop down for Lists be in alphabetical order?
2.  Advanced Search - Allow for searching based on list name (with wildcards) and return a list of subscribers that are members of that list

Many Thanks!

Dan

**Comment by bramley** [comment]
You can control the order in which phplist displays lists using the order for listing field 
![image](https://user-images.githubusercontent.com/3147688/36451406-dfffbf00-1688-11e8-94f9-7c1c55207c76.png)

The plugin displays lists in that order.

I don't understand your second point.

**Comment by DanMellor** [comment]
Thanks for the quick response Duncan, much appreciated.

For Item 2, we have 1000’s of subscriber lists and on many occasions, for internal processes, I will often need to provide the list of subscribers to a particular Subscriber list, therefore, the ability to search for a subscriber list in the Advanced search (rather than scrolling through 1000’s of Subscriber lists in the drop down) would be awesome

Hope this helps clarify the request



Dan Mellor


Continuous Improvement and Operations Manager

T +44 23 8092 6145    |    C +44 787 940 7335

The Boathouse, Unit 30/31 Town Quay
Southampton, Hampshire SO14 2AQ
cogecopeer1.com<http://www.cogecopeer1.com/>


[cid:image001.jpg@01D3AAF9.6EEA16D0]<http://www.cogecopeer1.com/>

[cid:image003.png@01D3AAF9.6EEA16D0]

**Comment by bramley** [comment]
That's a bit more than just a "tweak" so it is not something that I am interested in adding, sorry.
