### ISSUE TITLE
LISTUNSUBSCRIBEURL not working in subscribed/welcome email

### ISSUE THREAD

**Issue by jesse-thomas** [bramley/phplist-plugin-subscribers#16]
On a subscriber form, if the email for when they confirm their subscription has LISTUNSUBSCRIBEURL in it the email will not send

**Comment by jesse-thomas** [comment]
The email not sending has to do with a value in the session. 
I did get it to send but it has the text [LISTUNSUBSCRIBEURL] in the email instead of the value

**Comment by bramley** [comment]
The placeholders are for use in campaign emails, not in system emails. phplist doesn't provide hooks to allow a plugin to manipulate the content of a system email.

**Comment by jesse-thomas** [comment]
dang, I'll find another way to do it. thanks for the reply.
