### ISSUE TITLE
curl problem

### ISSUE THREAD

**Issue by Stephan345** [bramley/phplist-plugin-subscribers#18]
I get the following error message when uploading a very simple test file by curl. The user is nevertheless imported and the list is updated.
I use the latest versions of phplist (v3.6.12), common plugin (3.25.1), and subscribers (2.34.1).

curl -F list_id=2 -F import_file=@import_test2.csv "https://phplist.ismar.org/lists/admin/?page=import2&pi=SubscribersPlugin&secre382f3b3f6e67626"
<p class="information">Reading emails from file ...
..ok, 2 lines</p>
<script type="text/javascript">
        var parentJQuery = window.parent.jQuery;
        parentJQuery("#progressbar").updateProgress("0,1");
        </script><p>Trying to access array offset on value of type null</p><p>#0 /var/www/ud20_456/html/phplist/lists/admin/lib.php(89): phpList\plugin\Common\Exception::errorHandler()<br />
#1 /var/www/ud20_456/html/phplist/lists/admin/actions/import2.php(433): listName()<br />
#2 /var/www/ud20_456/html/phplist/lists/admin/plugins/SubscribersPlugin/Controller/Import2.php(96): require('...')<br />
#3 /var/www/ud20_456/html/phplist/lists/admin/plugins/SubscribersPlugin/Controller/Import2.php(118): phpList\plugin\SubscribersPlugin\Controller\Import2-&gt;importFile()<br />
#4 /var/www/ud20_456/html/phplist/lists/admin/plugins/Common/Controller.php(114): phpList\plugin\SubscribersPlugin\Controller\Import2-&gt;actionDefault()<br />
#5 /var/www/ud20_456/html/phplist/lists/admin/plugins/Common/Main.php(40): phpList\plugin\Common\Controller-&gt;run()<br />
#6 /var/www/ud20_456/html/phplist/lists/admin/plugins/SubscribersPlugin/import2.php(25): phpList\plugin\Common\Main::run()<br />
#7 /var/www/ud20_456/html/phplist/lists/admin/index.php(770): include('...')<br />
#8 {main}</p>

**Comment by bramley** [comment]
Thanks for reporting the problem. I think that it has been made visible by stricter error reporting with php 8. There is a new version of the plugin and you can update on the Manage Plugins page.

**Comment by Stephan345** [comment]
Thanks a million for this very fast fix and the great plugin. Now it seems to work.
