### ISSUE TITLE
Unsubscribe email notifications not working

### ISSUE THREAD

**Issue by mobeeniqbal** [bramley/phplist-plugin-subscribers#20]
Hello.
I have recently started using your plugin for PHP list and I really like the functionality. 1 very useful feature that PHP list offers is email notifications when a user subscribes and unsubscribes. At the moment when this plugin is disabled, PHP list will send notifications as usual both for subscriptions and unsubscriptions. However when the plugin is enabled, PHP list does not notify me via email when a user unsubscribes from individual lists, probably because the user has not been unsubscribed from all lists. Would it be possible to implement a feature to notify the admin via email when a user subscribes and unsubscribes from individual lists please?
I'm currently using PHP list 3.6.15 with version  2.38.0+20240520 of the plugin.
Please keep up the excellent work.
Kind regards,
Mo.

**Comment by bramley** [comment]
The way that I viewed this feature was as a shortcut to using the Preferences page. Clicking the link produced by using the `[LISTUNSUBSCRIBE]` placeholder has the same effect as going to the Preferences page and unchecking one of the lists. phpList doesn't notifiy the admin when a subscriber does that nor when they select another list.

But what you are asking for appears straightforward so I will look into it.

**Comment by mobeeniqbal** [comment]
Many thanks, it's much appreciated. I think the only notification that needs to be re-enabled is the unsubscribe notification as opposed to the user switching to another list. It's really useful to receive notifications when tracking the affectiveness of campaigns. We also run mailing lists that are accessed by visually impaired individuals and they sometimes click unsubscribe by accident. I didn't realise how much I'd miss the feature until it stopped working when we decided to use this plugin. Thanks again.

**Comment by bramley** [comment]
This is how the email for unsubscribing from a list will look
![image](https://github.com/user-attachments/assets/a1e6b8cf-685a-4906-9ca9-b0a70d992874)

**Comment by mobeeniqbal** [comment]
That's perfect, many thanks. I'd be happy to conduct beta testing if necessary before a general release is posted if it helps.

**Comment by bramley** [comment]
You can install a branch with the changes on the Manage Plugins page using the package URL
    `https://github.com/bramley/phplist-plugin-subscribers/archive/unsubscription_notification.zip`

**Comment by mobeeniqbal** [comment]
That's working perfectly, many thanks for implementing the feature so quickly. We really appreciate your time. Will this feature be merged in to the master branch for future updates? Or do we need to be careful when installing future updates for this plugin?

**Comment by bramley** [comment]
The plugin has its own processing to handle the link clicks, so I don't think it is possible to use the core phplist processing for unsubscribing in the way that you described.

You can now revert to the master branch by using this package URL
`https://github.com/bramley/phplist-plugin-subscribers/archive/master.zip`

**Comment by mobeeniqbal** [comment]
No problem, i'll revert back to the master branch. Many thanks once again for the prompt update.
