### ISSUE TITLE
Search by IP address

### ISSUE THREAD

**Issue by douglsmith** [bramley/phplist-plugin-subscribers#4]
It would be useful to add searching by IP address. The use case I've run into is a spammer who registered many subscriber addresses. Being able to search by IP would easily find additional accounts.

**Comment by bramley** [comment]
Amended the Subscriber History to search on the IP address used for subscriptions, unsubscribes etc.

**Comment by douglsmith** [comment]
Thanks @bramley. I tested searches with several IPs that would return a single record or multiple records. I also tested partial IPs. It's all working well for me.
