### ISSUE TITLE
FR: Sign-up Page Stats

### ISSUE THREAD

**Issue by justinputney** [bramley/phplist-plugin-subscribers#7]
I'd love to see statistics for which subscribe pages subscribers signed up on. I have multiple subscribe pages and I plan to add more. With some, I give away free tools. I also want to set up custom subscribe pages for autoresponder lists. I'd love to compare the traction that the different sign-up pages get.

**Comment by bramley** [comment]
Can you give an example of the statistics that you want to see?

**Comment by justinputney** [comment]
Yes, absolutely.

For example, right now I have 2 subscribe pages and I plan to add more.

![subscrpages](https://cloud.githubusercontent.com/assets/1245892/8574195/530f1802-254a-11e5-92ab-5f038a10f612.png)

Note that one page is just a sign up for the newsletter. The other one offers a free script with the newsletter. I would like to compare the performance of these two pages.

Without plugins, the best I can do is to look at each individual subscribers details to see which page they signed up on.

![subscrprof](https://cloud.githubusercontent.com/assets/1245892/8574234/7ed79afe-254a-11e5-9d88-d2ff2376551a.png)

The Subscriber History page is a huge step up because I can easily see a recent stream, with the subscribe page easy to find.

![subscrhist](https://cloud.githubusercontent.com/assets/1245892/8574268/ab8f3854-254a-11e5-9299-f296cd3aee49.png)

But that doesn't show me overall numbers or trends over time. It would be really helpful if I could see an overview similar to the campaign statistics.

![subscriberpagestats](https://cloud.githubusercontent.com/assets/1245892/8574297/d94daee2-254a-11e5-9da5-3fb17f08ea41.png)
