### ISSUE TITLE
Some Data

### ISSUE THREAD

**Issue by zlobica** [bramley/phplist-plugin-subscribers#8]
Hello.
Thanks so much for this plugin
I would like to ask you something
how can I display all the information?
As you can see in video, some of the data in Advanced Search in the table and in the filters are missing
http://screencast.com/t/qtoGomgvxTuc
Thank you in advance!

**Comment by bramley** [comment]
The plugin uses only 15 attributes. I found that having dozens of attributes, which one client had, did not display very well. This is mentioned in the help file
![screenshot from 2015-09-25 12 11 07](https://cloud.githubusercontent.com/assets/3147688/10099137/b8c80538-637e-11e5-9d15-2b7e6eeafd2b.png)
You can select which 15 attributes are used by altering the "Order of listing" on the Configure Attributes page, menu Config > Configure attributes. The plugin selects the first 15 ordered by that value.

**Comment by zlobica** [comment]
Bramley, thank you for your prompt response
Can you tell me please what I need to change in order to show more data for example 30 rows?
Thank you in advance!

**Comment by bramley** [comment]
The plugin does not provide a way of configuring the value of 15. You can change one of the plugin's files, line 90 of file SubscribersPlugin/Model/Details.php. Change the line from

            $this->attributeDAO = new CommonPlugin_DAO_Attribute($db);
to

            $this->attributeDAO = new CommonPlugin_DAO_Attribute($db, 20, 30);
The value 20 is the maximum display length of an attribute's name, the value 30 is the maximum number of attributes to display.

**Comment by zlobica** [comment]
It works :)
Thank you very much Duncan.
