### ISSUE TITLE
Full List Download

### ISSUE THREAD

**Issue by facilitator999** [bramley/phplist-plugin-subscribers#9]
When I search for users which is around 150,000 emails; the exported csv which is downloaded only shows around 30k users

**Comment by bramley** [comment]
Is the export actually completing? Depending on how long the processing is taking, I wonder whether either php or the browser is timing-out and you are receiving only a partial export.

I cannot repeat the problem when exporting about 70,000 subscribers, the downloaded file contains all the subscribers, but I have no way of testing with the number that you have. If you need to export subscribers then you might be better off using the core phplist export, but that exports only complete lists, not search results.

**Comment by facilitator999** [comment]
Would you like to see my server set up? What can I change in the server settings to improve this

**Comment by bramley** [comment]
> Is the export actually completing? 

You didn't answer my question. I would expect it to be fairly clear whether the download actually completes successfully or not.

**Comment by facilitator999** [comment]
I'm not sure, it appears not

**Comment by bramley** [comment]
Please can you clarify what the problem is, as I might have misunderstood it.

**Comment by facilitator999** [comment]
The figures shown by your search plugin ie emails addresses, does not show
in the CVS downloaded

**Comment by bramley** [comment]
Sorry, but it is still not clear. Unless you can explain what you did, what the result was, and what you were expecting then I cannot help.

**Comment by facilitator999** [comment]
1) This url shows mailing/admin/?page=details&pi=SubscribersPlugin&tk=7e6e9   (email address **116304** )

**Comment by facilitator999** [comment]
please clarify which part are you confused with?

**Comment by facilitator999** [comment]
This solved it

max_execution_time = 30 -> changed to 300
memory_limit = 128M -> changed to 512M

**Comment by bramley** [comment]
I wasn't sure whether you were expecting all subscribers to be exported or only those appearing in the search results. But thanks for explaining the solution.
